# Generated by Django 5.0.3 on 2024-04-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrimgg', '0002_alter_lobby_id_alter_player_elo_alter_player_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='in_queue',
            field=models.BooleanField(default=False),
        ),
    ]
