# Generated by Django 5.0.3 on 2024-04-01 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrimgg', '0003_lobby_in_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='banned_maps',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='match',
            name='banned_servers',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='match',
            name='maps',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='match',
            name='played_map',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='played_server',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='servers',
            field=models.JSONField(default=list),
        ),
        migrations.RemoveField(
            model_name='match',
            name='parties',
        ),
        migrations.AddField(
            model_name='match',
            name='parties',
            field=models.JSONField(default=dict),
        ),
    ]
