# Generated by Django 5.0.3 on 2024-04-01 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrimgg', '0004_match_banned_maps_match_banned_servers_match_maps_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='players',
        ),
    ]
