# Generated by Django 5.0.3 on 2024-04-01 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrimgg', '0005_remove_match_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='pregame_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
