# Generated by Django 5.2.7 on 2025-10-19 20:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('CONFIRMED', 'All players accepted'), ('SERVER_VETO', 'Server veto in progress'), ('VETO', 'Map veto in progress'), ('SIDE_SELECTION', 'Side selection in progress'), ('CREATING', 'Custom game being created'), ('READY', 'Ready to start'), ('IN_PROGRESS', 'Match started'), ('COMPLETED', 'Match finished'), ('CANCELLED', 'Match cancelled')], db_index=True, default='CONFIRMED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match_confirmation_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('team_a_lobbies', models.JSONField(help_text='List of lobby IDs in Team A')),
                ('team_b_lobbies', models.JSONField(help_text='List of lobby IDs in Team B')),
                ('team_a_players', models.JSONField(help_text='List of player data for Team A')),
                ('team_b_players', models.JSONField(help_text='List of player data for Team B')),
                ('team_a_captain_puuid', models.CharField(max_length=100)),
                ('team_b_captain_puuid', models.CharField(max_length=100)),
                ('server_pool', models.JSONField(default=list, help_text='Available servers for veto')),
                ('vetoed_servers', models.JSONField(default=list, help_text='List of vetoed server names')),
                ('server_veto_history', models.JSONField(default=list, help_text='History of server veto actions')),
                ('final_server', models.CharField(blank=True, max_length=20, null=True)),
                ('server_veto_turn', models.CharField(blank=True, help_text="'team_a' or 'team_b'", max_length=10, null=True)),
                ('server_veto_deadline', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('server_veto_started_at', models.DateTimeField(blank=True, null=True)),
                ('map_pool', models.JSONField(help_text='Available maps for veto')),
                ('vetoed_maps', models.JSONField(default=list, help_text='List of vetoed map names')),
                ('veto_history', models.JSONField(default=list, help_text='History of veto actions')),
                ('final_map', models.CharField(blank=True, max_length=50, null=True)),
                ('veto_turn', models.CharField(blank=True, help_text="'team_a' or 'team_b'", max_length=10, null=True)),
                ('veto_deadline', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('veto_started_at', models.DateTimeField(blank=True, null=True)),
                ('selected_side', models.CharField(blank=True, help_text="'attack' or 'defense'", max_length=10, null=True)),
                ('side_selector', models.CharField(blank=True, help_text='Which team selects side', max_length=10, null=True)),
                ('side_selection_deadline', models.DateTimeField(blank=True, null=True)),
                ('server_region', models.CharField(max_length=20)),
                ('constructor_puuid', models.CharField(blank=True, max_length=100, null=True)),
                ('pregame_id', models.CharField(blank=True, help_text='Valorant pregame ID', max_length=100, null=True)),
                ('coregame_id', models.CharField(blank=True, help_text='Valorant coregame ID', max_length=100, null=True)),
                ('team_a_score', models.IntegerField(default=0)),
                ('team_b_score', models.IntegerField(default=0)),
                ('current_round', models.IntegerField(default=0)),
                ('game_started_at', models.DateTimeField(blank=True, null=True)),
                ('game_ended_at', models.DateTimeField(blank=True, null=True)),
                ('match_quality', models.FloatField(default=0.0)),
                ('team_a_avg_mmr', models.FloatField(default=0.0)),
                ('team_b_avg_mmr', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'match_system_match',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['state', 'created_at'], name='match_syste_state_26d791_idx'), models.Index(fields=['veto_deadline'], name='match_syste_veto_de_6516fd_idx'), models.Index(fields=['pregame_id'], name='match_syste_pregame_102ea4_idx')],
            },
        ),
        migrations.CreateModel(
            name='MatchPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_puuid', models.CharField(db_index=True, max_length=100)),
                ('player_alias', models.CharField(max_length=100)),
                ('player_elo', models.IntegerField()),
                ('player_mmr', models.FloatField()),
                ('team', models.CharField(help_text="'team_a' or 'team_b'", max_length=10)),
                ('is_captain', models.BooleanField(default=False)),
                ('is_ready', models.BooleanField(default=False, help_text='Player ready for match')),
                ('joined_pregame', models.BooleanField(default=False, help_text='Player joined custom game')),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('join_attempts', models.IntegerField(default=0)),
                ('last_join_attempt', models.DateTimeField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('connection_issues', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='match_system.match')),
            ],
            options={
                'db_table': 'match_system_match_player',
                'indexes': [models.Index(fields=['match', 'joined_pregame'], name='match_syste_match_i_f48bb9_idx'), models.Index(fields=['player_puuid', 'match'], name='match_syste_player__5126f6_idx')],
                'unique_together': {('match', 'player_puuid')},
            },
        ),
        migrations.CreateModel(
            name='VetoAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('BAN', 'Map banned'), ('PICK', 'Map picked'), ('TIMEOUT', 'Timeout auto-action'), ('SERVER_VETO', 'Server vetoed')], max_length=15)),
                ('map_name', models.CharField(max_length=50)),
                ('team', models.CharField(help_text="'team_a' or 'team_b'", max_length=10)),
                ('player_puuid', models.CharField(blank=True, max_length=100, null=True)),
                ('sequence_number', models.IntegerField(help_text='Order in veto sequence')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('was_timeout', models.BooleanField(default=False)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veto_actions', to='match_system.match')),
            ],
            options={
                'db_table': 'match_system_veto_action',
                'ordering': ['match', 'sequence_number'],
                'indexes': [models.Index(fields=['match', 'sequence_number'], name='match_syste_match_i_d307a0_idx')],
            },
        ),
    ]
