# Generated by Django 5.2.7 on 2025-10-20 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='state',
            field=models.CharField(choices=[('CONFIRMED', 'All players accepted'), ('SERVER_VETO', 'Server veto in progress'), ('MAP_VETO', 'Map veto in progress'), ('SIDE_SELECTION', 'Side selection in progress'), ('CREATING', 'Custom game being created'), ('READY', 'Ready to start'), ('IN_PROGRESS', 'Match started'), ('COMPLETED', 'Match finished'), ('CANCELLED', 'Match cancelled')], db_index=True, default='CONFIRMED', max_length=20),
        ),
    ]
