# Generated by Django 5.2.7 on 2025-10-19 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0011_add_server_veto_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='final_server',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
