# Generated by Django 5.0.3 on 2024-03-30 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('average_elo', models.FloatField(default=0.0)),
                ('size', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('alias', models.CharField(max_length=100)),
                ('puuid', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=5)),
                ('elo', models.IntegerField(default=0)),
                ('karma', models.IntegerField(default=50)),
                ('rank', models.CharField(max_length=1)),
                ('team', models.CharField(max_length=100)),
                ('profile_picture', models.ImageField(upload_to='')),
                ('active_ban', models.BooleanField(default=False)),
                ('finish_ban', models.DateTimeField(auto_now_add=True)),
                ('pug_history', models.JSONField(default=dict)),
                ('league_history', models.JSONField(default=dict)),
                ('team_history', models.JSONField(default=dict)),
                ('team_active', models.JSONField(default=dict)),
                ('frags', models.IntegerField(default=0)),
                ('deaths', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('maxfrag', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('loss', models.IntegerField(default=0)),
                ('adr', models.FloatField(default=0.0)),
                ('highest_adr', models.FloatField(default=0.0)),
                ('acs', models.FloatField(default=0.0)),
                ('hs', models.FloatField(default=0.0)),
                ('rws', models.FloatField(default=0.0)),
                ('highest_rws', models.FloatField(default=0.0)),
                ('pug_rws', models.FloatField(default=0.0)),
                ('pug_frags', models.IntegerField(default=0)),
                ('pug_deaths', models.IntegerField(default=0)),
                ('pug_adr', models.FloatField(default=0.0)),
                ('league_adr', models.FloatField(default=0.0)),
                ('league_rws', models.FloatField(default=0.0)),
                ('league_frags', models.IntegerField(default=0)),
                ('league_deaths', models.IntegerField(default=0)),
                ('friends', models.ManyToManyField(blank=True, related_name='friend_set', to='scrimgg.player')),
                ('incoming_friend_requests', models.ManyToManyField(blank=True, related_name='incoming_requests', to='scrimgg.player')),
                ('outgoing_friend_requests', models.ManyToManyField(blank=True, related_name='outgoing_requests', to='scrimgg.player')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('finish_time', models.DateTimeField(auto_now_add=True)),
                ('match_info', models.JSONField(default=dict)),
                ('parties', models.ManyToManyField(related_name='lobbies', to='scrimgg.lobby')),
                ('players', models.ManyToManyField(related_name='matches', to='scrimgg.player')),
            ],
        ),
        migrations.AddField(
            model_name='lobby',
            name='lobby_leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_lobbies', to='scrimgg.player'),
        ),
        migrations.AddField(
            model_name='lobby',
            name='players',
            field=models.ManyToManyField(related_name='lobbies', to='scrimgg.player'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('division', models.CharField(max_length=100)),
                ('team_history', models.JSONField(default=dict)),
                ('active_roster', models.ManyToManyField(blank=True, related_name='active_teams', to='scrimgg.player')),
                ('players', models.ManyToManyField(related_name='teams', to='scrimgg.player')),
                ('substitute_roster', models.ManyToManyField(blank=True, related_name='substitute_teams', to='scrimgg.player')),
            ],
        ),
    ]
