# Generated by Django 5.0.3 on 2024-03-31 14:18
# Modified to handle bigint to UUID conversion properly

import uuid
from django.db import migrations, models, connection


def convert_lobby_id_to_uuid_forward(apps, schema_editor):
    """
    Convert Lobby.id from bigint to UUID.
    This handles both empty and populated tables.
    """
    with connection.cursor() as cursor:
        # Check if table exists
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_schema = 'public' 
                AND table_name = 'scrimgg_lobby'
            )
        """)
        if not cursor.fetchone()[0]:
            return
        
        # Check if column is already UUID type
        cursor.execute("""
            SELECT data_type 
            FROM information_schema.columns 
            WHERE table_name = 'scrimgg_lobby' 
            AND column_name = 'id'
        """)
        result = cursor.fetchone()
        if result and result[0] == 'uuid':
            # Already converted, skip
            return
        
        # Get row count
        cursor.execute("SELECT COUNT(*) FROM scrimgg_lobby")
        row_count = cursor.fetchone()[0]
        
        if row_count == 0:
            # Empty table - simple conversion
            cursor.execute("ALTER TABLE scrimgg_lobby DROP CONSTRAINT IF EXISTS scrimgg_lobby_pkey CASCADE")
            cursor.execute("ALTER TABLE scrimgg_lobby DROP COLUMN IF EXISTS id CASCADE")
            cursor.execute("""
                ALTER TABLE scrimgg_lobby 
                ADD COLUMN id UUID PRIMARY KEY DEFAULT gen_random_uuid()
            """)
        else:
            # Table has data - need careful migration
            # Step 1: Add temporary UUID column
            cursor.execute("ALTER TABLE scrimgg_lobby ADD COLUMN id_new UUID")
            
            # Step 2: Generate UUIDs for all existing rows
            cursor.execute("UPDATE scrimgg_lobby SET id_new = gen_random_uuid()")
            
            # Step 3: Update join table if it exists
            cursor.execute("""
                SELECT EXISTS (
                    SELECT FROM information_schema.tables 
                    WHERE table_schema = 'public' 
                    AND table_name = 'scrimgg_lobby_players'
                )
            """)
            join_table_exists = cursor.fetchone()[0]
            
            if join_table_exists:
                # Create a mapping table with old and new IDs
                cursor.execute("""
                    CREATE TEMP TABLE lobby_id_mapping (
                        old_id BIGINT,
                        new_id UUID
                    )
                """)
                cursor.execute("""
                    INSERT INTO lobby_id_mapping (old_id, new_id)
                    SELECT id, id_new FROM scrimgg_lobby
                """)
                
                # Drop foreign key constraint first
                cursor.execute("""
                    SELECT constraint_name 
                    FROM information_schema.table_constraints 
                    WHERE table_name = 'scrimgg_lobby_players' 
                    AND constraint_type = 'FOREIGN KEY'
                    AND constraint_name LIKE '%lobby_id%'
                """)
                fk_result = cursor.fetchone()
                if fk_result:
                    constraint_name = fk_result[0]
                    # Safe to format directly since constraint_name comes from information_schema
                    cursor.execute(
                        f'ALTER TABLE scrimgg_lobby_players DROP CONSTRAINT IF EXISTS "{constraint_name}" CASCADE'
                    )
                
                # Add temporary UUID column to join table
                cursor.execute("""
                    ALTER TABLE scrimgg_lobby_players 
                    ADD COLUMN lobby_id_new UUID
                """)
                
                # Update join table with new UUIDs using the mapping
                cursor.execute("""
                    UPDATE scrimgg_lobby_players lob
                    SET lobby_id_new = mapping.new_id
                    FROM lobby_id_mapping mapping
                    WHERE lob.lobby_id = mapping.old_id
                """)
                
                # Drop old column and rename new one
                cursor.execute("ALTER TABLE scrimgg_lobby_players DROP COLUMN lobby_id CASCADE")
                cursor.execute("ALTER TABLE scrimgg_lobby_players RENAME COLUMN lobby_id_new TO lobby_id")
                
                # Clean up temp table
                cursor.execute("DROP TABLE IF EXISTS lobby_id_mapping")
            
            # Step 4: Drop old primary key and id column
            cursor.execute("ALTER TABLE scrimgg_lobby DROP CONSTRAINT IF EXISTS scrimgg_lobby_pkey CASCADE")
            cursor.execute("ALTER TABLE scrimgg_lobby DROP COLUMN id CASCADE")
            
            # Step 5: Rename new column to id and make it primary key
            cursor.execute("ALTER TABLE scrimgg_lobby RENAME COLUMN id_new TO id")
            cursor.execute("ALTER TABLE scrimgg_lobby ADD PRIMARY KEY (id)")
            cursor.execute("ALTER TABLE scrimgg_lobby ALTER COLUMN id SET DEFAULT gen_random_uuid()")
            
            # Step 6: Recreate foreign key constraint on join table if it was updated
            if join_table_exists:
                # Drop constraint if it exists (shouldn't, but be safe)
                cursor.execute("""
                    DO $$
                    BEGIN
                        IF EXISTS (
                            SELECT 1 FROM information_schema.table_constraints 
                            WHERE constraint_name = 'scrimgg_lobby_players_lobby_id_fk'
                            AND table_name = 'scrimgg_lobby_players'
                        ) THEN
                            ALTER TABLE scrimgg_lobby_players 
                            DROP CONSTRAINT scrimgg_lobby_players_lobby_id_fk;
                        END IF;
                    END $$;
                """)
                cursor.execute("""
                    ALTER TABLE scrimgg_lobby_players 
                    ADD CONSTRAINT scrimgg_lobby_players_lobby_id_fk 
                    FOREIGN KEY (lobby_id) 
                    REFERENCES scrimgg_lobby(id) 
                    ON DELETE CASCADE
                """)


def convert_lobby_id_to_uuid_reverse(apps, schema_editor):
    """
    Reverse migration - convert UUID back to bigint
    Warning: This will lose UUID data and generate new sequential IDs
    """
    with connection.cursor() as cursor:
        cursor.execute("SELECT COUNT(*) FROM scrimgg_lobby")
        row_count = cursor.fetchone()[0]
        
        if row_count > 0:
            raise ValueError(
                "Cannot safely reverse UUID to bigint conversion with existing data. "
                "This would cause data loss. Manual intervention required."
            )
        
        # Only proceed if table is empty
        cursor.execute("ALTER TABLE scrimgg_lobby DROP CONSTRAINT IF EXISTS scrimgg_lobby_pkey CASCADE")
        cursor.execute("ALTER TABLE scrimgg_lobby DROP COLUMN IF EXISTS id CASCADE")
        cursor.execute("ALTER TABLE scrimgg_lobby ADD COLUMN id BIGSERIAL PRIMARY KEY")


class Migration(migrations.Migration):

    dependencies = [
        ('scrimgg', '0001_initial'),
    ]

    operations = [
        # Convert the database column from bigint to UUID
        migrations.RunPython(
            convert_lobby_id_to_uuid_forward,
            convert_lobby_id_to_uuid_reverse,
        ),
        # Update Django's model state to reflect UUID field (no SQL will run since column already exists)
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Database is already converted, nothing to do
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='lobby',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='elo',
            field=models.IntegerField(default=6493),
        ),
        migrations.AlterField(
            model_name='player',
            name='rank',
            field=models.CharField(default='S', max_length=1),
        ),
    ]
