# Generated by Django 5.0.3 on 2024-03-31 14:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrimgg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobby',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='elo',
            field=models.IntegerField(default=6493),
        ),
        migrations.AlterField(
            model_name='player',
            name='rank',
            field=models.CharField(default='S', max_length=1),
        ),
    ]
