# Generated by Django 5.0.3 on 2024-04-01 09:00

from django.db import migrations, models
from django.db import connection


def add_in_queue_if_not_exists(apps, schema_editor):
    """Add in_queue column only if it doesn't already exist."""
    with connection.cursor() as cursor:
        # Check if column already exists
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='scrimgg_lobby' AND column_name='in_queue'
        """)
        if not cursor.fetchone():
            # Column doesn't exist, add it
            cursor.execute("ALTER TABLE scrimgg_lobby ADD COLUMN in_queue BOOLEAN DEFAULT FALSE")
        # If column exists, do nothing (already in the database)


def reverse_add_in_queue(apps, schema_editor):
    """Remove in_queue column if it exists."""
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='scrimgg_lobby' AND column_name='in_queue'
        """)
        if cursor.fetchone():
            cursor.execute("ALTER TABLE scrimgg_lobby DROP COLUMN in_queue")


class Migration(migrations.Migration):

    dependencies = [
        ('scrimgg', '0002_alter_lobby_id_alter_player_elo_alter_player_rank'),
    ]

    operations = [
        # Separate database operation from Django state update
        # This allows us to conditionally add the column in the database
        # while still updating Django's migration state
        migrations.SeparateDatabaseAndState(
            # Database operation: conditionally add column
            database_operations=[
                migrations.RunPython(
                    add_in_queue_if_not_exists,
                    reverse_add_in_queue,
                ),
            ],
            # State operation: update Django's model state
            state_operations=[
                migrations.AddField(
                    model_name='lobby',
                    name='in_queue',
                    field=models.BooleanField(default=False),
                ),
            ],
        ),
    ]
