# Generated by Django 5.0.3 on 2024-04-01 09:31

from django.db import migrations, models
from django.db import connection


def add_match_fields_if_not_exist(apps, schema_editor):
    """Add match fields only if they don't already exist."""
    with connection.cursor() as cursor:
        # List of fields to add with their SQL types
        fields_to_add = [
            ('banned_maps', 'JSONB'),
            ('banned_servers', 'JSONB'),
            ('maps', 'JSONB'),
            ('played_map', 'VARCHAR(100)'),
            ('played_server', 'VARCHAR(100)'),
            ('servers', 'JSONB'),
        ]
        
        # Check and add each field if it doesn't exist
        for field_name, sql_type in fields_to_add:
            cursor.execute("""
                SELECT column_name 
                FROM information_schema.columns 
                WHERE table_name='scrimgg_match' AND column_name=%s
            """, [field_name])
            if not cursor.fetchone():
                # Column doesn't exist, add it
                if sql_type == 'JSONB':
                    cursor.execute(f"ALTER TABLE scrimgg_match ADD COLUMN {field_name} {sql_type} DEFAULT '[]'::jsonb")
                elif 'VARCHAR' in sql_type:
                    cursor.execute(f"ALTER TABLE scrimgg_match ADD COLUMN {field_name} {sql_type}")
        
        # Handle parties field: check if it exists and what type it is
        cursor.execute("""
            SELECT column_name, data_type 
            FROM information_schema.columns 
            WHERE table_name='scrimgg_match' AND column_name='parties'
        """)
        parties_info = cursor.fetchone()
        if parties_info:
            # parties exists, check if it's JSONB, if not, we need to convert it
            # But for safety, we'll just skip if it exists
            pass
        else:
            # parties doesn't exist, add it as JSONB
            cursor.execute("ALTER TABLE scrimgg_match ADD COLUMN parties JSONB DEFAULT '{}'::jsonb")


def reverse_add_match_fields(apps, schema_editor):
    """Remove match fields if they exist."""
    with connection.cursor() as cursor:
        fields_to_remove = [
            'banned_maps', 'banned_servers', 'maps', 'played_map', 
            'played_server', 'servers', 'parties'
        ]
        for field_name in fields_to_remove:
            cursor.execute("""
                SELECT column_name 
                FROM information_schema.columns 
                WHERE table_name='scrimgg_match' AND column_name=%s
            """, [field_name])
            if cursor.fetchone():
                cursor.execute(f"ALTER TABLE scrimgg_match DROP COLUMN {field_name}")


class Migration(migrations.Migration):

    dependencies = [
        ('scrimgg', '0003_lobby_in_queue'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # Database operation: conditionally add columns
            database_operations=[
                migrations.RunPython(
                    add_match_fields_if_not_exist,
                    reverse_add_match_fields,
                ),
            ],
            # State operation: update Django's model state
            state_operations=[
                migrations.AddField(
                    model_name='match',
                    name='banned_maps',
                    field=models.JSONField(default=list),
                ),
                migrations.AddField(
                    model_name='match',
                    name='banned_servers',
                    field=models.JSONField(default=list),
                ),
                migrations.AddField(
                    model_name='match',
                    name='maps',
                    field=models.JSONField(default=list),
                ),
                migrations.AddField(
                    model_name='match',
                    name='played_map',
                    field=models.CharField(blank=True, max_length=100, null=True),
                ),
                migrations.AddField(
                    model_name='match',
                    name='played_server',
                    field=models.CharField(blank=True, max_length=100, null=True),
                ),
                migrations.AddField(
                    model_name='match',
                    name='servers',
                    field=models.JSONField(default=list),
                ),
                migrations.RemoveField(
                    model_name='match',
                    name='parties',
                ),
                migrations.AddField(
                    model_name='match',
                    name='parties',
                    field=models.JSONField(default=dict),
                ),
            ],
        ),
    ]
