# Generated by Django 5.0.3 on 2024-04-01 09:52

from django.db import migrations
from django.db import connection


def remove_match_players_if_exists(apps, schema_editor):
    """Remove the scrimgg_match_players through table only if it exists."""
    with connection.cursor() as cursor:
        # Check if the through table exists
        cursor.execute("""
            SELECT table_name 
            FROM information_schema.tables 
            WHERE table_schema = 'public' AND table_name = 'scrimgg_match_players'
        """)
        if cursor.fetchone():
            # Table exists, drop it
            cursor.execute("DROP TABLE IF EXISTS scrimgg_match_players CASCADE")
        # If table doesn't exist, do nothing (already removed)


def reverse_remove_match_players(apps, schema_editor):
    """Reverse: This would recreate the through table, but we don't need to."""
    # No-op: We don't want to recreate a field that shouldn't exist
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('scrimgg', '0004_match_banned_maps_match_banned_servers_match_maps_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # Database operation: conditionally remove through table
            database_operations=[
                migrations.RunPython(
                    remove_match_players_if_exists,
                    reverse_remove_match_players,
                ),
            ],
            # State operation: update Django's model state (remove field)
            state_operations=[
                migrations.RemoveField(
                    model_name='match',
                    name='players',
                ),
            ],
        ),
    ]
