# Generated by Django 5.0.3 on 2024-04-01 20:46

from django.db import migrations, models
from django.db import connection


def add_pregame_id_if_not_exists(apps, schema_editor):
    """Add pregame_id column only if it doesn't already exist."""
    with connection.cursor() as cursor:
        # Check if column already exists
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='scrimgg_match' AND column_name='pregame_id'
        """)
        if not cursor.fetchone():
            # Column doesn't exist, add it
            cursor.execute("ALTER TABLE scrimgg_match ADD COLUMN pregame_id VARCHAR(100)")
        # If column exists, do nothing (already in the database)


def reverse_add_pregame_id(apps, schema_editor):
    """Remove pregame_id column if it exists."""
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='scrimgg_match' AND column_name='pregame_id'
        """)
        if cursor.fetchone():
            cursor.execute("ALTER TABLE scrimgg_match DROP COLUMN pregame_id")


class Migration(migrations.Migration):

    dependencies = [
        ('scrimgg', '0005_remove_match_players'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # Database operation: conditionally add column
            database_operations=[
                migrations.RunPython(
                    add_pregame_id_if_not_exists,
                    reverse_add_pregame_id,
                ),
            ],
            # State operation: update Django's model state
            state_operations=[
                migrations.AddField(
                    model_name='match',
                    name='pregame_id',
                    field=models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
    ]
