# Generated by Django 5.2.7 on 2025-10-10 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrimgg', '0006_match_pregame_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='profile_picture',
            field=models.ImageField(default='avatars/default/default_avatar.svg', upload_to='avatars/'),
        ),
    ]
