# Generated by Django 5.2.7 on 2025-10-11 13:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrimgg', '0007_alter_player_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lobby',
            name='elo_range',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='lobby',
            name='map_preferences',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='lobby',
            name='max_size',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='lobby',
            name='queue_type',
            field=models.CharField(default='pug', max_length=20),
        ),
        migrations.AddField(
            model_name='lobby',
            name='queued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lobby',
            name='server_preferences',
            field=models.JSONField(default=list),
        ),
    ]
