# Generated by Django 5.2.7 on 2025-10-11 15:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrimgg', '0008_lobby_created_at_lobby_elo_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='confirmation_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='constructor_puuid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='coregame_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='current_round',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='game_server',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='match',
            name='selected_map',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('confirmed', 'All Players Accepted'), ('starting', 'Creating Custom Game'), ('in_progress', 'Match Live'), ('paused', 'Match Paused'), ('completed', 'Match Finished'), ('cancelled', 'Match Cancelled')], default='confirmed', max_length=20),
        ),
        migrations.AddField(
            model_name='match',
            name='team_a_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='match',
            name='team_a_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='team_b_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='match',
            name='team_b_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='finish_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MatchRejoinToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejoin_tokens', to='scrimgg.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrimgg.player')),
            ],
            options={
                'indexes': [models.Index(fields=['token'], name='scrimgg_mat_token_db007c_idx'), models.Index(fields=['match', 'player'], name='scrimgg_mat_match_i_ed3413_idx')],
                'unique_together': {('match', 'player')},
            },
        ),
        migrations.CreateModel(
            name='MatchStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=10)),
                ('kills', models.IntegerField(default=0)),
                ('deaths', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('headshots', models.IntegerField(default=0)),
                ('bodyshots', models.IntegerField(default=0)),
                ('legshots', models.IntegerField(default=0)),
                ('damage_dealt', models.IntegerField(default=0)),
                ('damage_received', models.IntegerField(default=0)),
                ('adr', models.FloatField(default=0.0)),
                ('rws', models.FloatField(default=0.0)),
                ('headshot_percentage', models.FloatField(default=0.0)),
                ('kd_ratio', models.FloatField(default=0.0)),
                ('round_stats', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='scrimgg.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrimgg.player')),
            ],
            options={
                'indexes': [models.Index(fields=['match', 'team'], name='scrimgg_mat_match_i_2e230f_idx')],
                'unique_together': {('match', 'player')},
            },
        ),
    ]
