# Generated by Django 5.2.7 on 2025-10-11 23:21

from django.db import migrations, models
from django.db import connection


def add_player_fields_if_not_exist(apps, schema_editor):
    """Add player fields only if they don't already exist."""
    with connection.cursor() as cursor:
        fields_to_add = [
            ('games_played', 'INTEGER', 'DEFAULT 0'),
            ('is_in_placement', 'BOOLEAN', 'DEFAULT TRUE'),
            ('is_settled', 'BOOLEAN', 'DEFAULT FALSE'),
            ('last_game_timestamp', 'DOUBLE PRECISION', 'DEFAULT 0.0'),
            ('mmr', 'DOUBLE PRECISION', 'DEFAULT 4350.0'),
            ('trueskill_mu', 'DOUBLE PRECISION', 'DEFAULT 25.0'),
            ('trueskill_sigma', 'DOUBLE PRECISION', 'DEFAULT 9.0'),
        ]
        
        for field_name, sql_type, default in fields_to_add:
            cursor.execute("""
                SELECT column_name 
                FROM information_schema.columns 
                WHERE table_name='scrimgg_player' AND column_name=%s
            """, [field_name])
            if not cursor.fetchone():
                cursor.execute(f"ALTER TABLE scrimgg_player ADD COLUMN {field_name} {sql_type} {default}")


def reverse_add_player_fields(apps, schema_editor):
    """Remove player fields if they exist."""
    with connection.cursor() as cursor:
        fields_to_remove = [
            'games_played', 'is_in_placement', 'is_settled',
            'last_game_timestamp', 'mmr', 'trueskill_mu', 'trueskill_sigma'
        ]
        for field_name in fields_to_remove:
            cursor.execute("""
                SELECT column_name 
                FROM information_schema.columns 
                WHERE table_name='scrimgg_player' AND column_name=%s
            """, [field_name])
            if cursor.fetchone():
                cursor.execute(f"ALTER TABLE scrimgg_player DROP COLUMN {field_name}")


class Migration(migrations.Migration):

    dependencies = [
        ('scrimgg', '0009_match_completed_at_match_confirmation_completed_at_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    add_player_fields_if_not_exist,
                    reverse_add_player_fields,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='player',
                    name='games_played',
                    field=models.IntegerField(default=0),
                ),
                migrations.AddField(
                    model_name='player',
                    name='is_in_placement',
                    field=models.BooleanField(default=True),
                ),
                migrations.AddField(
                    model_name='player',
                    name='is_settled',
                    field=models.BooleanField(default=False),
                ),
                migrations.AddField(
                    model_name='player',
                    name='last_game_timestamp',
                    field=models.FloatField(default=0.0),
                ),
                migrations.AddField(
                    model_name='player',
                    name='mmr',
                    field=models.FloatField(default=4350.0),
                ),
                migrations.AddField(
                    model_name='player',
                    name='trueskill_mu',
                    field=models.FloatField(default=25.0),
                ),
                migrations.AddField(
                    model_name='player',
                    name='trueskill_sigma',
                    field=models.FloatField(default=9.0),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='elo',
            field=models.IntegerField(default=2750),
        ),
    ]
