# Generated by Django 5.2.7 on 2025-10-11 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrimgg', '0009_match_completed_at_match_confirmation_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='games_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='is_in_placement',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='player',
            name='is_settled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='last_game_timestamp',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='mmr',
            field=models.FloatField(default=4350.0),
        ),
        migrations.AddField(
            model_name='player',
            name='trueskill_mu',
            field=models.FloatField(default=25.0),
        ),
        migrations.AddField(
            model_name='player',
            name='trueskill_sigma',
            field=models.FloatField(default=9.0),
        ),
        migrations.AlterField(
            model_name='player',
            name='elo',
            field=models.IntegerField(default=2750),
        ),
    ]
