# Generated by Django 5.2.7 on 2025-10-17 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrimgg', '0010_add_join_tracking_fields'),
        ('scrimgg', '0010_player_games_played_player_is_in_placement_and_more'),
    ]

    operations = [
    ]
